name: Docker Build & Push - Reporting

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: nibscbioinformatics/viralevo-reporting
          tags: dev-git
          path: ./containers/viralevo-reporting
          always_pull: false
          push: true
